### PR TITLE
upgrade to .net6.0-windows

### PR DESCRIPTION
**Pull request by John0King**
- [x] upgrade to .net6
- [x] remove save on startup
- [x]  add combox to select the paint method 
- [ ]  implement save to disk

### CODE REVIEW

**Comment by mikeoliphant** [comment]
Thanks for the PR, but I have not yet migrated to .NET 6.0 / VS 2022.

I've thought about doing something similar to what you've done for selecting an example, but haven't yet gotten around to it. If you want to submit a PR that contains just those changes (and not the .NET 6.0 stuff), I'd be happy to merge it.

**Comment by John0King** [comment]
@mikeoliphant have you got VS2019  so we can continue to use the "Sdk style" `.csproj` file ?

**Comment by mikeoliphant** [comment]
I did a quick test of the PR, and it seems to work fine with VS2019 simply changing the TargetFramework to net5.0-windows.

Merging - thanks for the contribution.

**Comment by John0King** [comment]
@mikeoliphant 
a note:
  I drop a few `Painter` in this PR (because I live in China, and Can not connect to the server that  those Painters need to download images from ), maybe we can move the "download" part  into the `drawing` method , and with a try-catch to handle the download exception.
OR we can pre-download it into this repo.

**Comment by mikeoliphant** [comment]
I put the image-based examples back in, but it now catches the exceptions if the image can't be loaded.

**Pull request merged**
